### PR TITLE
Added group set topic API call

### PR DESCRIPTION
**Pull request by rrzaripov**
API call documentation: https://rocket.chat/docs/developer-guides/rest-api/groups/settopic/

### CODE REVIEW

**Comment by pipozzz** [comment]
Hello,
thank you for your contribution. 
Could you also create simple test for it, it looks good to me, so if we have test I'll merge it.

**Comment by rrzaripov** [comment]
@pipozzz yes, I will append tests in near time.

**Comment by pipozzz** [comment]
Any update on this? I would like to do a new release at the end of this month, or we just move this issue to new milestone?
Thanks

**Comment by rrzaripov** [comment]
@pipozzz sorry for late update, test added.

**Pull request merged**
